export { default as del } from './delete.svg'
export { default as accept } from "./accept.svg";
export { default as comment } from "./comment.svg";
export { default as pen } from "./pen.svg";
export { default as plus } from "./plus.svg";
export { default as userIcon } from "./user_icon.svg";
export { default as view } from "./view.svg";
export { default as send } from "./send.svg";
export { default as close } from "./close.svg";
